// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace OrderManage
{
	public partial class AddNewViewController : NSViewController
	{
        public OrderModel _order = new OrderModel("1","1",0);


        public AddNewViewController (IntPtr handle) : base (handle)
		{
		}

        [Export("Order")]
        public OrderModel Order
        {
            get { return _order; }
            set
            {
                WillChangeValue("Order");
                _order = value;
                DidChangeValue("Order");
            }
        }

        partial void AddButton(Foundation.NSObject sender)
        {

        }
    }
}
