// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace OrderManage
{
	public partial class TableViewController : NSViewController
	{
        public NSMutableArray _orders = new NSMutableArray();
        public OrderModel _order = new OrderModel("0", "0", 0);

        public TableViewController(IntPtr handle) : base(handle)
        {
        }

        [Export("orderModelArray")]
        public NSArray Orders
        {
            get { return _orders; }
        }

        [Export("addObject:")]
        public void AddOrder(OrderModel order)
        {
            WillChangeValue("orderModelArray");
            _orders.Add(order);
            DidChangeValue("orderModelArray");
        }

        [Export("insertObject:inOrderModelArrayAtIndex:")]
        public void InsertOrder(OrderModel order, nint index)
        {
            WillChangeValue("orderModelArray");
            _orders.Insert(order, index);
            DidChangeValue("orderModelArray");
        }

        [Export("removeObjectFromOrderModelArrayAtIndex:")]
        public void RemoveOrder(nint index)
        {
            WillChangeValue("orderModelArray");
            _orders.RemoveObject(index);
            DidChangeValue("orderModelArray");
        }

        [Export("setOrderModelArray:")]
        public void SetOrders(NSMutableArray array)
        {
            WillChangeValue("orderModelArray");
            _orders = array;
            DidChangeValue("orderModelArray");
        }

        [Export("Order")]
        public OrderModel Order
        {
            get { return _order; }
            set
            {
                WillChangeValue("Order");
                _order = value;
                DidChangeValue("Order");
            }
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }


        partial void AddNew(Foundation.NSObject sender)
        {
            string ID = IDText.StringValue;
            string Name = NameText.StringValue;
            int Value = ValueText.IntValue;

            _order = new OrderModel(ID, Name, Value);
            AddOrder(_order);
        }

        partial void deleteButn(Foundation.NSObject sender)
        {
            OrderModel chosen;
        }
        
    }
}
