// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace OrderManagement
{
	public partial class TableViewController : NSViewController
	{
        private NSMutableArray _orders = new NSMutableArray();

		public TableViewController (IntPtr handle) : base (handle)
		{
		}

        [Export("orderModelArray")]
        public NSArray Orders
        {
            get { return _orders; }
        }

        [Export("addObject:")]
        public void AddOrder(OrderModel order)
        {
            WillChangeValue("orderModelArray");
            _orders.Add(order);
            DidChangeValue("orderModelArray");
        }

        [Export("insertObject:inOrderModelArrayAtIndex:")]
        public void InsertOrder(OrderModel order, nint index)
        {
            WillChangeValue("orderModelArray");
            _orders.Insert(order, index);
            DidChangeValue("orderModelArray");
        }

        [Export("removeObjectFromOrderModelArrayAtIndex:")]
        public void RemoveOrder(nint index)
        {
            WillChangeValue("orderModelArray");
            _orders.RemoveObject(index);
            DidChangeValue("orderModelArray");
        }

        [Export("setOrderModelArray:")]
        public void SetOrders(NSMutableArray array)
        {
            WillChangeValue("orderModelArray");
            _orders = array;
            DidChangeValue("orderModelArray");
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();
            AddOrder(new OrderModel("0000", "All Storage", 10000));

        }
    }
}
